name: Test save cache functionalities

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      image_os:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  test:
    env:
      BUNDLE_GEMFILE: ./ruby/Gemfile

    name: ${{ inputs.image_os }} ${{ inputs.arch }} save cache
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python with cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r python/requirements.txt

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: go/go.sum

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.6'
          bundler-cache: true

      - name: Generate folders and files to cache
        run: |
          mkdir myfolder
          dd if=/dev/urandom of=myfolder/file1.txt bs=1M count=100
          mkdir myfolder2
          dd if=/dev/urandom of=myfolder2/file1.txt bs=1M count=150

      - name: Save folders and files
        uses: actions/cache/save@v4
        with:
          path: |
            myfolder
            myfolder2
          key: cached_folders
