name: Test ubuntu-2004

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubicloud-standard-2-ubuntu-2004

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print kernel version
        run: uname -mr

      - name: Print OS version
        run: lsb_release -a

      - name: Print environment variables
        run: printenv

      - name: Print PATH
        run: echo $PATH

      - name: Try to update apt-get
        run: sudo apt-get update

      - name: Check filesystem
        continue-on-error: true
        run: sudo fsck -nf
