name: Test ubuntu-2204
run-name: ubuntu-2204 ${{ inputs.arch }} ${{ inputs.triggered_by }}

on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options: [x64, arm64]
        default: x64
      triggered_by:
        required: false
        type: string

jobs:
  test_image:
    uses: ./.github/workflows/test_all.yml
    with:
      runner: ${{ inputs.arch == 'x64' && 'ubicloud-standard-2-ubuntu-2204' || 'ubicloud-standard-2-arm-ubuntu-2204' }}
      image_os: ubuntu22
      arch: ${{ inputs.arch }}
