name: Test ubuntu-2004

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubicloud, ubuntu-latest]
    name: CI ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check kernel version 1
        run: uname

      - name: Check kernel version
        run: uname -mr

      - name: Check OS version
        run: lsb_release -a

      - name: Print environment variables
        run: printenv

      - name: Print PATH
        run: echo $PATH

      - name: Try to update apt-get
        run: sudo apt-get update

      - name: Check filesystem
        continue-on-error: true
        run: sudo fsck -nf
