name: Test ruby cache code

on:
  workflow_call:
    inputs:
      runner_type:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.runner_type }}

    env:
      BUNDLE_GEMFILE: ./ruby/Gemfile

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true 

      - name: Get gem list
        run: gem list
